### ISSUE TITLE
entities.js error connecting to 1.7.9 server

### ISSUE THREAD

**Issue by NerdYouDontKnow** [andrewrk/mineflayer#188] opened 2014-05-27 23:04 UTC
```
/Users/andrew/node_modules/mineflayer/lib/plugins/entities.js:314
    delete entity.effects[effect.id];
                                ^
TypeError: Cannot read property 'id' of undefined
    at Client.<anonymous> (/Users/andrew/node_modules/mineflayer/lib/plugins/entities.js:314:33)
    at Client.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (/Users/andrew/node_modules/minecraft-protocol/lib/client.js:95:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

I'll admit, I'm connecting to a Minecraft 1.7 server. In theory, I am using the 1.7 version of minecraft-protocol as well.

After updating minecraft-protocol (again), I am getting a different error:
```
/Users/andrew/node_modules/mineflayer/lib/plugins/entities.js:345
      player.entity = null;
                    ^
TypeError: Cannot set property 'entity' of undefined
    at Client.<anonymous> (/Users/andrew/node_modules/mineflayer/lib/plugins/entities.js:345:21)
    at Client.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (/Users/andrew/node_modules/minecraft-protocol/lib/client.js:95:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

**Comment by deathcap** [comment] 2015-03-09 19:45
This was caused by the player_info packet protocol change I believe, fixed in https://github.com/andrewrk/mineflayer/pull/195 https://github.com/deathcap/mineflayer/commit/2f89a250f85f4f42971613d2f4586564e9a0edcc

**Comment by deathcap** [comment] 2015-03-11 05:48
fix merged, this can be closed

**Closed** 2015-03-11 11:12 UTC
